import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import 'package:tkween/src/helpers/colors.dart';
import 'package:tkween/src/helpers/constants.dart';
import 'package:tkween/src/helpers/screens.dart';
import 'package:tkween/src/helpers/snack_toast.dart';
import 'package:tkween/src/list_data/message_list.dart';
import 'package:tkween/src/models/chat_model.dart';
import 'package:tkween/src/providers/theme_provider.dart';
import 'package:tkween/src/widgets/custom_app_bar.dart';

part 'screens/chat_screen.dart';
part 'widgets/body_section.dart';
part 'widgets/build_chat_bubble.dart';
part 'widgets/build_chat_text_box.dart';
